site:
  build: .
  ports :
   - "80:80"
  volumes:
   - ./www:/var/www/html/
  links:
   - mysql:mysql
 
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "8080:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - mysql:mysql
mysql:
  image: mysql:5.5
  ports:
   - "3306:3306"  
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mysite
    - MYSQL_USER=mysite
    - MYSQL_PASSWORD=password

